import { useEffect, useState } from 'react';
import { Outlet } from 'react-router-dom';
import { Link, useLocation } from 'react-router-dom';
import { LayoutGrid } from 'lucide-react';
import { fetchBackendStatus, type BackendStatus } from '../services/api';

/** Format an ISO timestamp as a plain date, or null if it is unusable. */
function formatDate(iso?: string | null): string | null {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.toISOString().slice(0, 10);
}

/** Whole days between an ISO timestamp and now. */
function daysSince(iso?: string | null): number | null {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return Math.floor((Date.now() - d.getTime()) / 86_400_000);
}

export function Layout() {
  const location = useLocation();
  const path = location.pathname;
  const isHome = path === '/';
  const isSectors = path === '/sectors' || path.startsWith('/sectors/');
  const [status, setStatus] = useState<BackendStatus | null>(null);

  useEffect(() => {
    fetchBackendStatus().then(setStatus);
  }, []);

  const asOf = formatDate(status?.dataAsOf);
  const age = daysSince(status?.dataAsOf);
  const stale = age != null && age > 30;

  return (
    <div className="flex min-h-screen flex-col bg-surface-dark">
      <header className="sticky top-0 z-50 border-b border-zinc-800/80 bg-surface-dark/95 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-6 py-4">
          <Link to="/" className="text-xl font-bold text-zinc-100 hover:text-white transition-colors">
            Scholes <span className="text-gold">Options</span>
          </Link>

          <nav className="flex items-center gap-1">
            <Link
              to="/"
              className={`rounded-lg px-4 py-2 text-sm font-medium transition-colors ${
                isHome ? 'text-gold' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              Home
            </Link>
            <Link
              to="/sectors"
              className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors ${
                isSectors ? 'text-gold' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <LayoutGrid className="h-4 w-4" />
              Sectors
            </Link>
          </nav>

          <div className="flex items-center gap-3">
            <Link
              to="/"
              className="rounded-full bg-accent-green px-5 py-2.5 text-sm font-semibold text-white hover:opacity-90 transition-opacity"
            >
              Explore
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-6xl flex-1 px-6">
        <Outlet />
      </main>

      <footer className="mt-16 border-t border-zinc-800/80 bg-surface-dark">
        <div className="mx-auto flex max-w-6xl flex-col gap-2 px-6 py-6 text-xs text-zinc-500 sm:flex-row sm:items-center sm:justify-between">
          <p className="max-w-2xl leading-relaxed">
            <span className="font-medium text-zinc-400">Educational project — not financial advice.</span>{' '}
            Scores and signals are generated by a Black–Scholes and sentiment model over a
            point-in-time data snapshot. Nothing here is a recommendation to buy or sell any
            security. Options data is a snapshot, not a live feed.
          </p>
          <p className="shrink-0 sm:text-right">
            {asOf ? (
              <>
                <span className={stale ? 'text-amber-400' : 'text-zinc-400'}>Data as of {asOf}</span>
                {stale && (
                  <span className="block text-amber-400/80">
                    ({age} days old — may be stale)
                  </span>
                )}
              </>
            ) : (
              <span className="text-zinc-600">Data snapshot date unavailable</span>
            )}
          </p>
        </div>
      </footer>
    </div>
  );
}
